function onUpdate(elapsed)
if getPropertyFromClass('PlayState', 'curStage') == 'DaveHouseNight' then
    setProperty('dad.color', getColorFromHex('878787'))
    setProperty('boyfriend.color', getColorFromHex('878787'))
    setProperty('gf.color', getColorFromHex('878787'))
setProperty('grass.color', getColorFromHex('878787'))
setProperty('hills.color', getColorFromHex('878787'))
setProperty('hills2.color', getColorFromHex('878787'))
setProperty('gate.color', getColorFromHex('878787'))
elseif getPropertyFromClass('PlayState', 'curStage') == 'dave-night-poster' then
    setProperty('dad.color', getColorFromHex('878787'))
    setProperty('boyfriend.color', getColorFromHex('878787'))
    setProperty('gf.color', getColorFromHex('878787'))
elseif getPropertyFromClass('PlayState', 'curStage') == 'SplitathonFarmNight' then
    setProperty('dad.color', getColorFromHex('878787'))
    setProperty('boyfriend.color', getColorFromHex('878787'))
    setProperty('gf.color', getColorFromHex('878787'))
    setProperty('flatgrass.color', getColorFromHex('878787'))
    setProperty('farm.color', getColorFromHex('878787'))
   setProperty('hills.color', getColorFromHex('878787'))
   setProperty('ground.color', getColorFromHex('878787'))
   setProperty('corn1.color', getColorFromHex('878787'))
   setProperty('corn2.color', getColorFromHex('878787'))
   setProperty('cornbag.color', getColorFromHex('878787'))
   setProperty('sign.color', getColorFromHex('878787'))
   setProperty('picnic.color', getColorFromHex('878787'))
   setProperty('bgTristan.color', getColorFromHex('878787'))
   setProperty('bgDave.color', getColorFromHex('878787'))
   setProperty('bgBambi.color', getColorFromHex('878787'))
   setProperty('bambi.color', getColorFromHex('878787'))
   setProperty('bambi2.color', getColorFromHex('878787'))
elseif getPropertyFromClass('PlayState', 'curStage') == 'house' then
setProperty('grass.color', getColorFromHex('878787'))
setProperty('hills.color', getColorFromHex('878787'))
setProperty('gate.color', getColorFromHex('878787'))
    setProperty('dad.color', getColorFromHex('878787'))
    setProperty('boyfriend.color', getColorFromHex('878787'))
    setProperty('gf.color', getColorFromHex('878787'))
elseif getPropertyFromClass('PlayState', 'curStage') == 'FarmNight' then
    setProperty('dad.color', getColorFromHex('878787'))
    setProperty('boyfriend.color', getColorFromHex('878787'))
    setProperty('gf.color', getColorFromHex('878787'))
    setProperty('flatgrass.color', getColorFromHex('878787'))
    setProperty('farm.color', getColorFromHex('878787'))
   setProperty('hills.color', getColorFromHex('878787'))
   setProperty('ground.color', getColorFromHex('878787'))
   setProperty('corn1.color', getColorFromHex('878787'))
   setProperty('corn2.color', getColorFromHex('878787'))
   setProperty('cornbag.color', getColorFromHex('878787'))
   setProperty('sign.color', getColorFromHex('878787'))
   setProperty('bambi.color', getColorFromHex('878787'))
   setProperty('bambi2.color', getColorFromHex('878787'))
elseif getPropertyFromClass('PlayState', 'curStage') == 'unfair' then
    setProperty('dad.color', getColorFromHex('878787'))
    setProperty('boyfriend.color', getColorFromHex('878787'))
    setProperty('gf.color', getColorFromHex('878787'))
end
end

